// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4hP6nTqWZ38SWvbrCq9fFS
// Component: gu4tQRhoaMCD

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import PageLayout from "../../PageLayout"; // plasmic-import: u5k9gpYL7hvi/component
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdSelect } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariantsipt9Py8JurHq } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ipt9py8JURHq/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 4hP6nTqWZ38SWvbrCq9fFS/projectcss
import sty from "./PlasmicNewThread.module.css"; // plasmic-import: gu4tQRhoaMCD/css

import image6UPxKEno1BR7 from "./images/image6.svg"; // plasmic-import: uPxKEno1b_r7/picture

createPlasmicElementProxy;

export type PlasmicNewThread__VariantMembers = {};
export type PlasmicNewThread__VariantsArgs = {};
type VariantPropType = keyof PlasmicNewThread__VariantsArgs;
export const PlasmicNewThread__VariantProps = new Array<VariantPropType>();

export type PlasmicNewThread__ArgsType = {};
type ArgPropType = keyof PlasmicNewThread__ArgsType;
export const PlasmicNewThread__ArgProps = new Array<ArgPropType>();

export type PlasmicNewThread__OverridesType = {
  root?: Flex__<"div">;
  pageLayout?: Flex__<typeof PageLayout>;
  img?: Flex__<typeof PlasmicImg__>;
  h1?: Flex__<"h1">;
  form2?: Flex__<typeof FormWrapper>;
  columns?: Flex__<"div">;
  input2?: Flex__<typeof AntdInput>;
  select2?: Flex__<typeof AntdSelect>;
  textArea2?: Flex__<typeof AntdTextArea>;
  button?: Flex__<typeof AntdButton>;
};

export interface DefaultNewThreadProps {
  className?: string;
}

const $$ = {};

function PlasmicNewThread__RenderFunc(props: {
  variants: PlasmicNewThread__VariantsArgs;
  args: PlasmicNewThread__ArgsType;
  overrides: PlasmicNewThread__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "id",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "form2.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "form2",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "input2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "select2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "textArea2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "tmpemail",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "form2.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "form2",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    categories: usePlasmicDataOp(() => {
      return {
        sourceId: "msPJThy8kgSaraQnjyXF2t",
        opId: "82225a4b-f0f3-4728-a79d-c6a56c44a264",
        userArgs: {},
        cacheKey: `plasmic.$.82225a4b-f0f3-4728-a79d-c6a56c44a264.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsipt9Py8JurHq()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
          >
            <DataCtxReader__>
              {$ctx => (
                <div
                  className={classNames(projectcss.all, sty.freeBox___9CnNm)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__nkWGx)}
                  >
                    <PlasmicImg__
                      data-plasmic-name={"img"}
                      data-plasmic-override={overrides.img}
                      alt={""}
                      className={classNames(sty.img)}
                      displayHeight={"auto"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"32%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"32px"}
                      loading={"lazy"}
                      src={{
                        src: image6UPxKEno1BR7,
                        fullWidth: 150,
                        fullHeight: 150,
                        aspectRatio: 1
                      }}
                    />

                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1
                      )}
                    >
                      {"New Thread"}
                    </h1>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__seK8T)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__id44O)}
                    >
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.form2),
                          extendedOnValuesChange:
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "value",
                              ["form2", "value"],
                              FormWrapper_Helpers
                            ),
                          formItems: [
                            { label: "Name", name: "name", inputType: "Text" },
                            {
                              label: "Message",
                              name: "message",
                              inputType: "Text Area"
                            }
                          ],
                          initialValues: (() => {
                            try {
                              return {
                                created_by: currentUser.email
                              };
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })(),
                          labelCol: { span: 8, horizontalOnly: true },
                          layout: "vertical",
                          mode: undefined,
                          onFinish: async values => {
                            const $steps = {};

                            $steps["updateId"] = true
                              ? (() => {
                                  const actionArgs = {
                                    variable: {
                                      objRoot: $state,
                                      variablePath: ["id"]
                                    },
                                    operation: 0,
                                    value: globalThis.crypto?.randomUUID()
                                  };
                                  return (({
                                    variable,
                                    value,
                                    startIndex,
                                    deleteCount
                                  }) => {
                                    if (!variable) {
                                      return;
                                    }
                                    const { objRoot, variablePath } = variable;

                                    $stateSet(objRoot, variablePath, value);
                                    return value;
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["updateId"] != null &&
                              typeof $steps["updateId"] === "object" &&
                              typeof $steps["updateId"].then === "function"
                            ) {
                              $steps["updateId"] = await $steps["updateId"];
                            }

                            $steps["updateTmpemail"] = true
                              ? (() => {
                                  const actionArgs = {
                                    variable: {
                                      objRoot: $state,
                                      variablePath: ["tmpemail"]
                                    },
                                    operation: 0,
                                    value: currentUser.email
                                  };
                                  return (({
                                    variable,
                                    value,
                                    startIndex,
                                    deleteCount
                                  }) => {
                                    if (!variable) {
                                      return;
                                    }
                                    const { objRoot, variablePath } = variable;

                                    $stateSet(objRoot, variablePath, value);
                                    return value;
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["updateTmpemail"] != null &&
                              typeof $steps["updateTmpemail"] === "object" &&
                              typeof $steps["updateTmpemail"].then ===
                                "function"
                            ) {
                              $steps["updateTmpemail"] = await $steps[
                                "updateTmpemail"
                              ];
                            }

                            $steps["tutorialdbCreate"] = true
                              ? (() => {
                                  const actionArgs = {
                                    dataOp: {
                                      sourceId: "msPJThy8kgSaraQnjyXF2t",
                                      opId: "b4bb129e-d85b-4db3-b787-22bf8b4e3098",
                                      userArgs: {
                                        variables: [
                                          $state.form2.value.category_id,
                                          $state.id,
                                          $state.form2.value.title
                                        ]
                                      },
                                      cacheKey: null,
                                      invalidatedKeys: ["plasmic_refresh_all"],
                                      roleId: null
                                    }
                                  };
                                  return (async ({
                                    dataOp,
                                    continueOnError
                                  }) => {
                                    try {
                                      const response =
                                        await executePlasmicDataOp(dataOp, {
                                          userAuthToken:
                                            dataSourcesCtx?.userAuthToken,
                                          user: dataSourcesCtx?.user
                                        });
                                      await plasmicInvalidate(
                                        dataOp.invalidatedKeys
                                      );
                                      return response;
                                    } catch (e) {
                                      if (!continueOnError) {
                                        throw e;
                                      }
                                      return e;
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["tutorialdbCreate"] != null &&
                              typeof $steps["tutorialdbCreate"] === "object" &&
                              typeof $steps["tutorialdbCreate"].then ===
                                "function"
                            ) {
                              $steps["tutorialdbCreate"] = await $steps[
                                "tutorialdbCreate"
                              ];
                            }

                            $steps["tutorialdbCreate"] = true
                              ? (() => {
                                  const actionArgs = {
                                    dataOp: {
                                      sourceId: "msPJThy8kgSaraQnjyXF2t",
                                      opId: "b472a847-041e-476a-85f6-d414fc87991f",
                                      userArgs: {
                                        variables: [
                                          $state.form2.value.body,
                                          $state.tmpemail,
                                          $state.id
                                        ]
                                      },
                                      cacheKey: null,
                                      invalidatedKeys: ["plasmic_refresh_all"],
                                      roleId: null
                                    }
                                  };
                                  return (async ({
                                    dataOp,
                                    continueOnError
                                  }) => {
                                    try {
                                      const response =
                                        await executePlasmicDataOp(dataOp, {
                                          userAuthToken:
                                            dataSourcesCtx?.userAuthToken,
                                          user: dataSourcesCtx?.user
                                        });
                                      await plasmicInvalidate(
                                        dataOp.invalidatedKeys
                                      );
                                      return response;
                                    } catch (e) {
                                      if (!continueOnError) {
                                        throw e;
                                      }
                                      return e;
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["tutorialdbCreate"] != null &&
                              typeof $steps["tutorialdbCreate"] === "object" &&
                              typeof $steps["tutorialdbCreate"].then ===
                                "function"
                            ) {
                              $steps["tutorialdbCreate"] = await $steps[
                                "tutorialdbCreate"
                              ];
                            }

                            $steps["goToHome"] = true
                              ? (() => {
                                  const actionArgs = {
                                    destination: `/thread/${(() => {
                                      try {
                                        return $state.id;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return undefined;
                                        }
                                        throw e;
                                      }
                                    })()}`
                                  };
                                  return (({ destination }) => {
                                    if (
                                      typeof destination === "string" &&
                                      destination.startsWith("#")
                                    ) {
                                      document
                                        .getElementById(destination.substr(1))
                                        .scrollIntoView({ behavior: "smooth" });
                                    } else {
                                      location.assign(destination);
                                    }
                                  })?.apply(null, [actionArgs]);
                                })()
                              : undefined;
                            if (
                              $steps["goToHome"] != null &&
                              typeof $steps["goToHome"] === "object" &&
                              typeof $steps["goToHome"].then === "function"
                            ) {
                              $steps["goToHome"] = await $steps["goToHome"];
                            }
                          },
                          onIsSubmittingChange:
                            generateStateOnChangePropForCodeComponents(
                              $state,
                              "isSubmitting",
                              ["form2", "isSubmitting"],
                              FormWrapper_Helpers
                            ),
                          ref: ref => {
                            $refs["form2"] = ref;
                          },
                          requiredMark: "optional",
                          wrapperCol: { span: 16, horizontalOnly: true }
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "form2.value"
                            },
                            {
                              name: "isSubmitting",
                              plasmicStateName: "form2.isSubmitting"
                            }
                          ],
                          [],
                          FormWrapper_Helpers ?? {},
                          child$Props
                        );

                        return (
                          <FormWrapper
                            data-plasmic-name={"form2"}
                            data-plasmic-override={overrides.form2}
                            {...child$Props}
                          >
                            <Stack__
                              as={"div"}
                              data-plasmic-name={"columns"}
                              data-plasmic-override={overrides.columns}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.columns
                              )}
                            >
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__tHpNw
                                )}
                              >
                                <FormItemWrapper
                                  className={classNames(
                                    "__wab_instance",
                                    sty.formField__ewfaa
                                  )}
                                  label={
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__apAp4
                                      )}
                                    >
                                      {"Title"}
                                    </div>
                                  }
                                  name={"title"}
                                  rules={[{ ruleType: "required" }]}
                                >
                                  {(() => {
                                    const child$Props = {
                                      className: classNames(
                                        "__wab_instance",
                                        sty.input2
                                      ),
                                      onChange:
                                        generateStateOnChangePropForCodeComponents(
                                          $state,
                                          "value",
                                          ["input2", "value"],
                                          AntdInput_Helpers
                                        ),
                                      value: generateStateValueProp($state, [
                                        "input2",
                                        "value"
                                      ])
                                    };
                                    initializeCodeComponentStates(
                                      $state,
                                      [
                                        {
                                          name: "value",
                                          plasmicStateName: "input2.value"
                                        }
                                      ],
                                      [],
                                      AntdInput_Helpers ?? {},
                                      child$Props
                                    );

                                    return (
                                      <AntdInput
                                        data-plasmic-name={"input2"}
                                        data-plasmic-override={overrides.input2}
                                        {...child$Props}
                                      />
                                    );
                                  })()}
                                </FormItemWrapper>
                              </div>
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.column__wDjcU
                                )}
                              >
                                <FormItemWrapper
                                  className={classNames(
                                    "__wab_instance",
                                    sty.formField__jb4Jk
                                  )}
                                  label={
                                    <div
                                      className={classNames(
                                        projectcss.all,
                                        projectcss.__wab_text,
                                        sty.text__z6XnL
                                      )}
                                    >
                                      {"Category"}
                                    </div>
                                  }
                                  name={"category_id"}
                                  rules={[{ ruleType: "required" }]}
                                >
                                  <AntdSelect
                                    data-plasmic-name={"select2"}
                                    data-plasmic-override={overrides.select2}
                                    className={classNames(
                                      "__wab_instance",
                                      sty.select2
                                    )}
                                    defaultStylesClassName={classNames(
                                      projectcss.root_reset,
                                      projectcss.plasmic_default_styles,
                                      projectcss.plasmic_mixins,
                                      projectcss.plasmic_tokens,
                                      plasmic_antd_5_hostless_css.plasmic_tokens,
                                      plasmic_plasmic_rich_components_css.plasmic_tokens
                                    )}
                                    onChange={generateStateOnChangeProp(
                                      $state,
                                      ["select2", "value"]
                                    )}
                                    options={(() => {
                                      try {
                                        return $queries.categories.data.map(
                                          c => ({
                                            value: c.id,
                                            label: c.name
                                          })
                                        );
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return [
                                            {
                                              value: "option1",
                                              label: "Option 1"
                                            },
                                            {
                                              value: "option2",
                                              label: "Option 2"
                                            }
                                          ];
                                        }
                                        throw e;
                                      }
                                    })()}
                                    placeholder={"Select..."}
                                    popupScopeClassName={sty["select2__popup"]}
                                    value={generateStateValueProp($state, [
                                      "select2",
                                      "value"
                                    ])}
                                  />
                                </FormItemWrapper>
                              </div>
                            </Stack__>
                            <FormItemWrapper
                              className={classNames(
                                "__wab_instance",
                                sty.formField__ftJnx
                              )}
                              label={
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__krglQ
                                  )}
                                >
                                  {"Body"}
                                </div>
                              }
                              name={"body"}
                              rules={[{ ruleType: "required" }]}
                            >
                              {(() => {
                                const child$Props = {
                                  className: classNames(
                                    "__wab_instance",
                                    sty.textArea2
                                  ),
                                  onChange:
                                    generateStateOnChangePropForCodeComponents(
                                      $state,
                                      "value",
                                      ["textArea2", "value"],
                                      AntdTextArea_Helpers
                                    ),
                                  value: generateStateValueProp($state, [
                                    "textArea2",
                                    "value"
                                  ])
                                };
                                initializeCodeComponentStates(
                                  $state,
                                  [
                                    {
                                      name: "value",
                                      plasmicStateName: "textArea2.value"
                                    }
                                  ],
                                  [],
                                  AntdTextArea_Helpers ?? {},
                                  child$Props
                                );

                                return (
                                  <AntdTextArea
                                    data-plasmic-name={"textArea2"}
                                    data-plasmic-override={overrides.textArea2}
                                    {...child$Props}
                                  />
                                );
                              })()}
                            </FormItemWrapper>
                            <FormItemWrapper
                              className={classNames(
                                "__wab_instance",
                                sty.formField__hq1B
                              )}
                              label={
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__qehZt
                                  )}
                                >
                                  {"Label"}
                                </div>
                              }
                              noLabel={true}
                            >
                              <AntdButton
                                data-plasmic-name={"button"}
                                data-plasmic-override={overrides.button}
                                className={classNames(
                                  "__wab_instance",
                                  sty.button
                                )}
                                onClick={async () => {
                                  const $steps = {};
                                }}
                                submitsForm={true}
                                type={"primary"}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text___2OjkF
                                  )}
                                >
                                  {"Post"}
                                </div>
                              </AntdButton>
                            </FormItemWrapper>
                          </FormWrapper>
                        );
                      })()}
                    </Stack__>
                  </Stack__>
                </div>
              )}
            </DataCtxReader__>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageLayout",
    "img",
    "h1",
    "form2",
    "columns",
    "input2",
    "select2",
    "textArea2",
    "button"
  ],
  pageLayout: [
    "pageLayout",
    "img",
    "h1",
    "form2",
    "columns",
    "input2",
    "select2",
    "textArea2",
    "button"
  ],
  img: ["img"],
  h1: ["h1"],
  form2: ["form2", "columns", "input2", "select2", "textArea2", "button"],
  columns: ["columns", "input2", "select2"],
  input2: ["input2"],
  select2: ["select2"],
  textArea2: ["textArea2"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  img: typeof PlasmicImg__;
  h1: "h1";
  form2: typeof FormWrapper;
  columns: "div";
  input2: typeof AntdInput;
  select2: typeof AntdSelect;
  textArea2: typeof AntdTextArea;
  button: typeof AntdButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewThread__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewThread__VariantsArgs;
    args?: PlasmicNewThread__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNewThread__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNewThread__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNewThread__ArgProps,
          internalVariantPropNames: PlasmicNewThread__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNewThread__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNewThread";
  } else {
    func.displayName = `PlasmicNewThread.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const PageGuard: React.FC<P> = props => (
    <PlasmicPageGuard__
      minRole={"211523eb-67b5-4df9-9e02-a2e1e4674c01"}
      appId={"4hP6nTqWZ38SWvbrCq9fFS"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

function withUsePlasmicAuth<P extends object>(
  WrappedComponent: React.ComponentType<P>
) {
  const WithUsePlasmicAuthComponent: React.FC<P> = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "4hP6nTqWZ38SWvbrCq9fFS"
    });

    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicNewThread = Object.assign(
  // Top-level PlasmicNewThread renders the root element
  withUsePlasmicAuth(withPlasmicPageGuard(makeNodeComponent("root"))),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    img: makeNodeComponent("img"),
    h1: makeNodeComponent("h1"),
    form2: makeNodeComponent("form2"),
    columns: makeNodeComponent("columns"),
    input2: makeNodeComponent("input2"),
    select2: makeNodeComponent("select2"),
    textArea2: makeNodeComponent("textArea2"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicNewThread
    internalVariantProps: PlasmicNewThread__VariantProps,
    internalArgProps: PlasmicNewThread__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "New Thread - Community Forum",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicNewThread;
/* prettier-ignore-end */
